Repository netceteragroup/skele, pull requests merged in 2018-12, with the labels that each got.

#124 feat(core): memoize the normalize function
  packages/core/src/data/__tests__/element-benchmarks.js
  packages/core/src/data/__tests__/element.js
  packages/core/src/data/element.js
  packages/core/src/registry/Registry.js
  packages/core/src/registry/__tests__/Registry.js
Labels: core, performance

#122 perf(core): new implementation of zippers
  packages/classic/src/enhance/impl.js
  packages/classic/src/enrich/impl.js
  packages/classic/src/transform/impl.js
  packages/core/package.json
  packages/core/src/__tests__/index.js
  packages/core/src/vendor/zippa/LICENSE
  packages/core/src/vendor/zippa/array_zipper.js
  packages/core/src/vendor/zippa/index.js
  packages/core/src/vendor/zippa/visit.js
  packages/core/src/vendor/zippa/walk.js
  packages/core/src/vendor/zippa/zipper.js
  packages/core/src/zip/__tests__/edit.js
  packages/core/src/zip/__tests__/elementZipper.js
  packages/core/src/zip/__tests__/fixture/navigation.json
  packages/core/src/zip/__tests__/walk-benchmark.js
  packages/core/src/zip/__tests__/walk.js
  packages/core/src/zip/__tests__/zipper.js
  packages/core/src/zip/edit.js
  packages/core/src/zip/elementZipper.js
  packages/core/src/zip/impl.js
  packages/core/src/zip/index.js
  packages/core/src/zip/reduce.js
  packages/core/src/zip/walk.js
  yarn.lock
Labels: performance, zippers

#127 chore: upgrade dependencies
  package.json
  yarn.lock
Labels: chore

#128 feat(core): editAt
  packages/core/src/zip/__tests__/edit.js
  packages/core/src/zip/edit.js
Labels: zippers

#129 feat(core): skeleZip
  packages/core/src/index.js
  packages/core/src/zip/elementZipper.js
  packages/core/src/zip/skele/__tests__/zipperImpl.js
  packages/core/src/zip/skele/index.js
  packages/core/src/zip/skele/zipperImpl.js
Labels: performance, zippers
